spring:
  profiles:
    active:
    - local
---

spring:
  profiles:
  - local
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
      
      
  datasource:
    url: jdbc:mysql://13.209.90.58/kproject?characterEncoding=UTF-8&serverTimezone=UTC
    username: root  
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  session:
      jdbc:
        initialize-schema: always
server:
  port: 80
 

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
      init-parameters:
         development: true
    session:
      timeout: 7200
      
  error:
      whitelabel:
        enabled: false
mybatis:
  type-aliases-package: com.Kproject.example.domain
  mapper-locations: mapper/**/*.xml
  
logging:
  config: classpath:logback-spring.xml
